#!/bin/sh
# Writes config.php from the environment on every start (so a variable change takes effect
# on redeploy), and moves IMathAS's writable directories onto the /data volume.
set -e
cd /var/www/html

# Exactly one Apache MPM, enforced at start (apt's apache2 update re-enables mpm_event;
# Apache refuses to start with two). Printed so the deploy log shows what was loaded.
echo "apache mods-enabled MPMs before: $(ls /etc/apache2/mods-enabled | grep -i mpm | tr '\n' ' ')"
for m in mpm_event mpm_worker; do
  if [ -e "/etc/apache2/mods-enabled/$m.load" ] || [ -e "/etc/apache2/mods-enabled/$m.conf" ]; then a2dismod -q "$m" || true; fi
done
a2enmod -q mpm_prefork >/dev/null 2>&1 || true
echo "apache mods-enabled MPMs after: $(ls /etc/apache2/mods-enabled | grep -i mpm | tr '\n' ' ')"
echo "apache LoadModule mpm lines: $(grep -rl 'mpm_' /etc/apache2/*.conf /etc/apache2/conf-enabled /etc/apache2/sites-enabled 2>/dev/null | tr '\n' ' ')"

: "${DB_HOST:?DB_HOST is required}"
: "${DB_NAME:?DB_NAME is required}"
: "${DB_USER:?DB_USER is required}"
DB_PORT="${DB_PORT:-3306}"
IMAS_ROOT="${IMAS_ROOT:-}"                # "" when served at the domain root
INSTALL_NAME="${IMAS_INSTALLNAME:-IMathAS}"
SEND_FROM="${IMAS_SENDFROM:-imathas@example.com}"

cat > config.php <<PHP
<?php
//IMathAS config — generated by docker/entrypoint.sh from environment variables. Do not edit.
\$dbserver = "${DB_HOST}:${DB_PORT}";
\$dbname = "${DB_NAME}";
\$dbusername = "${DB_USER}";
\$dbpassword = "${DB_PASSWORD}";
error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);
\$installname = "${INSTALL_NAME}";
\$loginprompt = "Username";
\$longloginprompt = "Enter a username.  Use only numbers, letters, or the _ character.";
\$loginformat = '/^[\\w+\\-]+\$/';
\$emailconfirmation = false;
\$sendfrom = "${SEND_FROM}";
\$colorshift = true;
\$imasroot = "${IMAS_ROOT}";
\$httpmode = (isset(\$_SERVER['HTTPS']) && \$_SERVER['HTTPS'] == 'on')
    || (isset(\$_SERVER['HTTP_X_FORWARDED_PROTO']) && \$_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')
    ? 'https://' : 'http://';
\$GLOBALS['basesiteurl'] = \$httpmode . Sanitize::domainNameWithPort(\$_SERVER['HTTP_HOST']) . \$imasroot;
\$mathimgurl = "http://www.imathas.com/cgi-bin/mimetex.cgi";
\$enablebasiclti = true;
\$allownongrouplibs = false;
\$allowcourseimport = true;
\$allowmacroinstall = true;
\$CFG['GEN']['newpasswords'] = 'only';
try {
  \$DBH = new PDO("mysql:host=${DB_HOST};port=${DB_PORT};dbname=${DB_NAME}", \$dbusername, \$dbpassword);
  \$DBH->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_WARNING);
  \$GLOBALS["DBH"] = \$DBH;
} catch (PDOException \$e) {
  die("<p>Could not connect to database: <b>" . \$e->getMessage() . "</b></p></div></body></html>");
}
\$DBH->query("set session sql_mode=''");
unset(\$dbserver);
unset(\$dbusername);
unset(\$dbpassword);
PHP

# The three personalisation files install.php would have copied.
for f in infoheader loginpage newinstructor; do
  [ -f "$f.php" ] || cp "$f.php.dist" "$f.php"
done

# Writable directories -> the volume (survive redeploys). Seed each from the image on first run.
mkdir -p /data
for d in filestore course/files assessment/libs assessment/qimages filter/graph/imgs admin/import; do
  name=$(echo "$d" | tr '/' '_')
  if [ ! -d "/data/$name" ]; then
    mkdir -p "/data/$name"
    if [ -d "$d" ] && [ ! -L "$d" ]; then cp -a "$d/." "/data/$name/" 2>/dev/null || true; fi
  fi
  rm -rf "$d"
  ln -s "/data/$name" "$d"
done
chown -R www-data:www-data /data config.php

exec "$@"
